version: '3.1'
services:
  db:
    container_name: data-base
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "6543:5432"
    env_file:
      - ".env"
    network_mode: "host"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    network_mode: "host"
    env_file:
      - ".env"

  db_cron_update:
    network_mode: "host"
    container_name: db_cron_update
    build:
      context: /cron

