version: '3.1'
services:
  db:
    container_name: mysql_db
    image: mysql:5.6
    restart: always
    command: --init-file /db/db.sql
    hostname: 127.0.99.3
    volumes:
      - ./db/db.sql:/db/db.sql
    env_file:
      - .env
    ports:
      - 3308:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    hostname: 127.0.0.4
    ports:
      - "8082:8080"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"

  db_cron_update:
    container_name: db_cron_update
    build:
      context: /cron

