CREATE TABLE IF NOT EXISTS RUS_FIGIS(
ID              SERIAL  PRIMARY KEY NOT NULL,
TICKER          CHAR(20),
LONG_OR_SHORT   BOOLEAN
);

ALTER TABLE RUS_FIGIS OWNER TO POSTGRES;

CREATE UNIQUE INDEX rus_figis_id_uindex ON RUS_FIGIS (ID);