CREATE TABLE IF NOT EXISTS USD_FIGIS(
ID              SERIAL  PRIMARY KEY NOT NULL,
TICKER          CHAR(20),
LONG_OR_SHORT   BOOLEAN
);

ALTER TABLE USD_FIGIS OWNER TO POSTGRES;

CREATE UNIQUE INDEX usd_figis_id_uindex ON USD_FIGIS (ID);